#!/usr/bin/env node
/*
 * Bundles rtl-core.js + rtl.css into rtl-payload.js, producing a single
 * self-contained IIFE with no imports — which is what both the CDP injector
 * and the userscript need.
 */
const fs = require('fs');
const path = require('path');

const SRC = __dirname;
const OUT = path.join(SRC, '..', 'dist', 'claude-rtl.bundle.js');

const core = fs.readFileSync(path.join(SRC, 'rtl-core.js'), 'utf8');
const css = fs.readFileSync(path.join(SRC, 'rtl.css'), 'utf8');
const payload = fs.readFileSync(path.join(SRC, 'rtl-payload.js'), 'utf8');

const bundle = payload
  .replace('__RTL_CORE__', () => core)
  .replace('__RTL_CSS__', () => JSON.stringify(css));

if (bundle.includes('__RTL_CORE__') || bundle.includes('__RTL_CSS__')) {
  console.error('build: placeholder left unreplaced');
  process.exit(1);
}

const header =
  '/* claude-rtl — generated by src/build.js. Edit files in src/, not this. */\n';

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, header + bundle);
console.log('built ' + path.relative(process.cwd(), OUT) +
  ' (' + bundle.length + ' bytes)');
